ddb.py and update-cognito-user-ids

diff --git a/backend-flask/bin/db/setup b/backend-flask/bin/db/setup
--- a/backend-flask/bin/db/setup
+++ b/backend-flask/bin/db/setup
@@ -1,5 +1,5 @@
 #! /usr/bin/bash
--e # stop if it fails at any point
+set -e # stop if it fails at any point
 CYAN='\033[1;36m'
 NO_COLOR='\033[0m'
 LABEL="db-setup"
@@ -8,8 +8,9 @@ printf "${CYAN}== ${LABEL}${NO_COLOR}\n"
 echo "db-setup"
 
 
-bin_path="$(find . -type d -name "bin" -path "./backend-flask/db")"
+bin_path="$(find . -type d -name "db" -path "./backend-flask/bin")"
 
+echo $bin_path
 echo $bin_path
 
 if [ "$1" == "prod" ]; then
@@ -18,10 +19,12 @@ if [ "$1" == "prod" ]; then
     source "$bin_path/create" "prod"
     source "$bin_path/schema-load" "prod"
     source "$bin_path/seed" "prod"
+    source "$bin_path/update-cognito-user-ids" "prod"
 
 else
     source "$bin_path/drop"
     source "$bin_path/create"
     source "$bin_path/schema-load"
     source "$bin_path/seed"
+    source "$bin_path/update-cognito-user-ids"
 fi
